[E 140415 10:17:54 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:17:54 web:1635] 500 GET /db (54.184.112.97) 55.81ms
[E 140415 10:17:59 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:17:59 web:1635] 500 GET /db (54.184.112.97) 44.27ms
[E 140415 10:18:07 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:18:07 web:1635] 500 GET /db (54.184.112.97) 3.64ms
[E 140415 10:18:10 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:18:10 web:1635] 500 GET /db (54.184.112.97) 5.64ms
[E 140415 10:18:10 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:18:10 web:1635] 500 GET /db (54.184.112.97) 3.45ms
[E 140415 10:18:28 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:18:28 web:1635] 500 GET /db (54.184.112.97) 4.37ms
[E 140415 10:18:28 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:18:28 web:1635] 500 GET /db (54.184.112.97) 3.82ms
[E 140415 10:18:34 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:18:34 web:1635] 500 GET /db (54.184.112.97) 3.34ms
[E 140415 10:18:38 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:18:38 web:1635] 500 GET /db (54.184.112.97) 4.98ms
[E 140415 10:18:42 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:18:42 web:1635] 500 GET /db (54.184.112.97) 7.43ms
[E 140415 10:18:43 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:18:43 web:1635] 500 GET /db (54.184.112.97) 4.74ms
[E 140415 10:18:44 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:18:44 web:1635] 500 GET /db (54.184.112.97) 6.04ms
[E 140415 10:18:46 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:18:46 web:1635] 500 GET /db (54.184.112.97) 6.31ms
[E 140415 10:18:49 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:18:49 web:1635] 500 GET /db (54.184.112.97) 5.68ms
[E 140415 10:18:49 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:18:49 web:1635] 500 GET /db (54.184.112.97) 4.93ms
[E 140415 10:18:50 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:18:50 web:1635] 500 GET /db (54.184.112.97) 8.08ms
[E 140415 10:18:52 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:18:52 web:1635] 500 GET /db (54.184.112.97) 5.64ms
[E 140415 10:18:53 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:18:53 web:1635] 500 GET /db (54.184.112.97) 6.89ms
[E 140415 10:18:54 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:18:54 web:1635] 500 GET /db (54.184.112.97) 5.40ms
[E 140415 10:18:59 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:18:59 web:1635] 500 GET /db (54.184.112.97) 9.29ms
[E 140415 10:19:00 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:00 web:1635] 500 GET /db (54.184.112.97) 10.42ms
[E 140415 10:19:01 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:01 web:1635] 500 GET /db (54.184.112.97) 7.99ms
[E 140415 10:19:06 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:06 web:1635] 500 GET /db (54.184.112.97) 10.79ms
[E 140415 10:19:07 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:07 web:1635] 500 GET /db (54.184.112.97) 6.94ms
[E 140415 10:19:08 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:08 web:1635] 500 GET /db (54.184.112.97) 9.73ms
[E 140415 10:19:09 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:09 web:1635] 500 GET /db (54.184.112.97) 9.00ms
[E 140415 10:19:09 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:09 web:1635] 500 GET /db (54.184.112.97) 9.79ms
[E 140415 10:19:10 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:10 web:1635] 500 GET /db (54.184.112.97) 8.72ms
[E 140415 10:19:10 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:10 web:1635] 500 GET /db (54.184.112.97) 9.88ms
[E 140415 10:19:11 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:11 web:1635] 500 GET /db (54.184.112.97) 9.49ms
[E 140415 10:19:12 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:12 web:1635] 500 GET /db (54.184.112.97) 14.14ms
[E 140415 10:19:12 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:12 web:1635] 500 GET /db (54.184.112.97) 7.73ms
[E 140415 10:19:16 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:16 web:1635] 500 GET /db (54.184.112.97) 24.77ms
[E 140415 10:19:17 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:17 web:1635] 500 GET /db (54.184.112.97) 19.31ms
[E 140415 10:19:17 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:17 web:1635] 500 GET /db (54.184.112.97) 21.61ms
[E 140415 10:19:20 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:20 web:1635] 500 GET /db (54.184.112.97) 17.17ms
[E 140415 10:19:20 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:20 web:1635] 500 GET /db (54.184.112.97) 16.50ms
[E 140415 10:19:21 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:21 web:1635] 500 GET /db (54.184.112.97) 20.11ms
[E 140415 10:19:22 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:22 web:1635] 500 GET /db (54.184.112.97) 18.23ms
[E 140415 10:19:23 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:23 web:1635] 500 GET /db (54.184.112.97) 17.47ms
[E 140415 10:19:24 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:24 web:1635] 500 GET /db (54.184.112.97) 43.54ms
[E 140415 10:19:25 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:25 web:1635] 500 GET /db (54.184.112.97) 20.08ms
[E 140415 10:19:32 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:32 web:1635] 500 GET /db (54.184.112.97) 42.44ms
[E 140415 10:19:36 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:36 web:1635] 500 GET /db (54.184.112.97) 37.65ms
[E 140415 10:19:37 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:37 web:1635] 500 GET /db (54.184.112.97) 37.61ms
[E 140415 10:19:39 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:39 web:1635] 500 GET /db (54.184.112.97) 42.84ms
[E 140415 10:19:40 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:40 web:1635] 500 GET /db (54.184.112.97) 48.13ms
[E 140415 10:19:40 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:40 web:1635] 500 GET /db (54.184.112.97) 37.02ms
[E 140415 10:19:42 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:42 web:1635] 500 GET /db (54.184.112.97) 39.05ms
[E 140415 10:19:42 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:42 web:1635] 500 GET /db (54.184.112.97) 37.23ms
[E 140415 10:19:43 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:43 web:1635] 500 GET /db (54.184.112.97) 34.31ms
[E 140415 10:19:44 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:44 web:1635] 500 GET /db (54.184.112.97) 76.75ms
[E 140415 10:19:46 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:46 web:1635] 500 GET /db (54.184.112.97) 37.10ms
[E 140415 10:19:53 web:1228] Uncaught exception GET /queries?queries=2 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=2', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:53 web:1635] 500 GET /queries?queries=2 (54.184.112.97) 5.17ms
[E 140415 10:19:53 web:1228] Uncaught exception GET /queries?queries=2 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=2', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:19:53 web:1635] 500 GET /queries?queries=2 (54.184.112.97) 3.84ms
[E 140415 10:20:06 web:1228] Uncaught exception GET /queries?queries=2 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=2', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:06 web:1635] 500 GET /queries?queries=2 (54.184.112.97) 53.31ms
[E 140415 10:20:09 web:1228] Uncaught exception GET /queries?queries=2 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=2', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:09 web:1635] 500 GET /queries?queries=2 (54.184.112.97) 45.81ms
[E 140415 10:20:10 web:1228] Uncaught exception GET /queries?queries=2 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=2', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:10 web:1635] 500 GET /queries?queries=2 (54.184.112.97) 87.31ms
[E 140415 10:20:10 web:1228] Uncaught exception GET /queries?queries=2 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=2', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:10 web:1635] 500 GET /queries?queries=2 (54.184.112.97) 91.82ms
[E 140415 10:20:11 web:1228] Uncaught exception GET /queries?queries=2 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=2', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:11 web:1635] 500 GET /queries?queries=2 (54.184.112.97) 75.73ms
[E 140415 10:20:21 web:1228] Uncaught exception GET /queries?queries=1 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=1', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:21 web:1635] 500 GET /queries?queries=1 (54.184.112.97) 55.93ms
[E 140415 10:20:22 web:1228] Uncaught exception GET /queries?queries=1 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=1', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:22 web:1635] 500 GET /queries?queries=1 (54.184.112.97) 48.80ms
[E 140415 10:20:28 web:1228] Uncaught exception GET /queries?queries=1 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=1', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:28 web:1635] 500 GET /queries?queries=1 (54.184.112.97) 42.23ms
[E 140415 10:20:28 web:1228] Uncaught exception GET /queries?queries=1 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=1', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:28 web:1635] 500 GET /queries?queries=1 (54.184.112.97) 52.80ms
[E 140415 10:20:31 web:1228] Uncaught exception GET /queries?queries=1 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=1', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:31 web:1635] 500 GET /queries?queries=1 (54.184.112.97) 47.24ms
[E 140415 10:20:32 web:1228] Uncaught exception GET /queries?queries=1 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=1', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:32 web:1635] 500 GET /queries?queries=1 (54.184.112.97) 42.36ms
[E 140415 10:20:32 web:1228] Uncaught exception GET /queries?queries=1 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=1', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:32 web:1635] 500 GET /queries?queries=1 (54.184.112.97) 52.69ms
[E 140415 10:20:37 web:1228] Uncaught exception GET /queries?queries=5 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=5', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:37 web:1635] 500 GET /queries?queries=5 (54.184.112.97) 143.07ms
[E 140415 10:20:41 web:1228] Uncaught exception GET /queries?queries=5 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=5', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:41 web:1635] 500 GET /queries?queries=5 (54.184.112.97) 195.13ms
[E 140415 10:20:44 web:1228] Uncaught exception GET /queries?queries=5 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=5', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:44 web:1635] 500 GET /queries?queries=5 (54.184.112.97) 279.91ms
[E 140415 10:20:46 web:1228] Uncaught exception GET /queries?queries=5 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=5', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:46 web:1635] 500 GET /queries?queries=5 (54.184.112.97) 172.38ms
[E 140415 10:20:46 web:1228] Uncaught exception GET /queries?queries=5 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=5', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:46 web:1635] 500 GET /queries?queries=5 (54.184.112.97) 123.65ms
[E 140415 10:20:47 web:1228] Uncaught exception GET /queries?queries=5 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=5', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:47 web:1635] 500 GET /queries?queries=5 (54.184.112.97) 201.07ms
[E 140415 10:20:48 web:1228] Uncaught exception GET /queries?queries=5 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=5', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:48 web:1635] 500 GET /queries?queries=5 (54.184.112.97) 118.17ms
[E 140415 10:20:51 web:1228] Uncaught exception GET /queries?queries=5 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=5', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:51 web:1635] 500 GET /queries?queries=5 (54.184.112.97) 189.03ms
[E 140415 10:20:56 web:1228] Uncaught exception GET /queries?queries=10 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=10', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:56 web:1635] 500 GET /queries?queries=10 (54.184.112.97) 252.55ms
[E 140415 10:20:59 web:1228] Uncaught exception GET /queries?queries=10 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=10', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:20:59 web:1635] 500 GET /queries?queries=10 (54.184.112.97) 320.74ms
[E 140415 10:21:00 web:1228] Uncaught exception GET /queries?queries=10 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=10', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:00 web:1635] 500 GET /queries?queries=10 (54.184.112.97) 422.51ms
[E 140415 10:21:01 web:1228] Uncaught exception GET /queries?queries=10 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=10', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:01 web:1635] 500 GET /queries?queries=10 (54.184.112.97) 201.19ms
[E 140415 10:21:01 web:1228] Uncaught exception GET /queries?queries=10 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=10', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:01 web:1635] 500 GET /queries?queries=10 (54.184.112.97) 323.47ms
[E 140415 10:21:03 web:1228] Uncaught exception GET /queries?queries=10 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=10', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:03 web:1635] 500 GET /queries?queries=10 (54.184.112.97) 319.52ms
[E 140415 10:21:05 web:1228] Uncaught exception GET /queries?queries=10 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=10', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:05 web:1635] 500 GET /queries?queries=10 (54.184.112.97) 334.99ms
[E 140415 10:21:08 web:1228] Uncaught exception GET /queries?queries=10 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=10', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:08 web:1635] 500 GET /queries?queries=10 (54.184.112.97) 351.37ms
[E 140415 10:21:12 web:1228] Uncaught exception GET /queries?queries=15 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:12 web:1635] 500 GET /queries?queries=15 (54.184.112.97) 283.16ms
[E 140415 10:21:13 web:1228] Uncaught exception GET /queries?queries=15 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:13 web:1635] 500 GET /queries?queries=15 (54.184.112.97) 288.38ms
[E 140415 10:21:18 web:1228] Uncaught exception GET /queries?queries=15 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:18 web:1635] 500 GET /queries?queries=15 (54.184.112.97) 375.64ms
[E 140415 10:21:18 web:1228] Uncaught exception GET /queries?queries=15 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:18 web:1635] 500 GET /queries?queries=15 (54.184.112.97) 282.05ms
[E 140415 10:21:19 web:1228] Uncaught exception GET /queries?queries=15 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:19 web:1635] 500 GET /queries?queries=15 (54.184.112.97) 277.80ms
[E 140415 10:21:19 web:1228] Uncaught exception GET /queries?queries=15 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:19 web:1635] 500 GET /queries?queries=15 (54.184.112.97) 418.58ms
[E 140415 10:21:20 web:1228] Uncaught exception GET /queries?queries=15 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:20 web:1635] 500 GET /queries?queries=15 (54.184.112.97) 215.33ms
[E 140415 10:21:23 web:1228] Uncaught exception GET /queries?queries=15 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:23 web:1635] 500 GET /queries?queries=15 (54.184.112.97) 220.98ms
[E 140415 10:21:23 web:1228] Uncaught exception GET /queries?queries=15 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:23 web:1635] 500 GET /queries?queries=15 (54.184.112.97) 312.60ms
[E 140415 10:21:24 web:1228] Uncaught exception GET /queries?queries=15 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:24 web:1635] 500 GET /queries?queries=15 (54.184.112.97) 800.90ms
[E 140415 10:21:29 web:1228] Uncaught exception GET /queries?queries=20 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=20', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:29 web:1635] 500 GET /queries?queries=20 (54.184.112.97) 668.05ms
[E 140415 10:21:31 web:1228] Uncaught exception GET /queries?queries=20 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=20', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:31 web:1635] 500 GET /queries?queries=20 (54.184.112.97) 628.46ms
[E 140415 10:21:31 web:1228] Uncaught exception GET /queries?queries=20 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=20', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:31 web:1635] 500 GET /queries?queries=20 (54.184.112.97) 772.18ms
[E 140415 10:21:33 web:1228] Uncaught exception GET /queries?queries=20 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=20', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:33 web:1635] 500 GET /queries?queries=20 (54.184.112.97) 682.61ms
[E 140415 10:21:34 web:1228] Uncaught exception GET /queries?queries=20 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=20', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:34 web:1635] 500 GET /queries?queries=20 (54.184.112.97) 545.85ms
[E 140415 10:21:34 web:1228] Uncaught exception GET /queries?queries=20 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=20', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:34 web:1635] 500 GET /queries?queries=20 (54.184.112.97) 553.80ms
[E 140415 10:21:35 web:1228] Uncaught exception GET /queries?queries=20 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=20', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:35 web:1635] 500 GET /queries?queries=20 (54.184.112.97) 625.59ms
[E 140415 10:21:36 web:1228] Uncaught exception GET /queries?queries=20 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=20', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:36 web:1635] 500 GET /queries?queries=20 (54.184.112.97) 549.88ms
[E 140415 10:21:37 web:1228] Uncaught exception GET /queries?queries=20 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=20', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:37 web:1635] 500 GET /queries?queries=20 (54.184.112.97) 552.99ms
[E 140415 10:21:37 web:1228] Uncaught exception GET /queries?queries=20 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=20', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:37 web:1635] 500 GET /queries?queries=20 (54.184.112.97) 751.97ms
[E 140415 10:21:37 web:1228] Uncaught exception GET /queries?queries=20 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=20', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:37 web:1635] 500 GET /queries?queries=20 (54.184.112.97) 458.64ms
[E 140415 10:21:39 web:1228] Uncaught exception GET /queries?queries=20 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=20', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:39 web:1635] 500 GET /queries?queries=20 (54.184.112.97) 623.16ms
[E 140415 10:21:41 web:1228] Uncaught exception GET /queries?queries=20 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=20', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/pypy/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:21:41 web:1635] 500 GET /queries?queries=20 (54.184.112.97) 681.27ms
