[E 140415 10:08:21 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:08:21 web:1635] 500 GET /db (54.184.112.97) 138.04ms
[E 140415 10:08:26 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:08:26 web:1635] 500 GET /db (54.184.112.97) 247.76ms
[E 140415 10:08:40 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:08:40 web:1635] 500 GET /db (54.184.112.97) 5.65ms
[E 140415 10:09:19 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:09:19 web:1635] 500 GET /db (54.184.112.97) 25.17ms
[E 140415 10:09:48 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:09:48 web:1635] 500 GET /db (54.184.112.97) 106.62ms
[E 140415 10:09:51 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:09:51 web:1635] 500 GET /db (54.184.112.97) 64.67ms
[E 140415 10:09:51 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:09:51 web:1635] 500 GET /db (54.184.112.97) 78.62ms
[E 140415 10:09:51 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:09:51 web:1635] 500 GET /db (54.184.112.97) 77.98ms
[E 140415 10:09:58 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:09:58 web:1635] 500 GET /db (54.184.112.97) 73.25ms
[E 140415 10:10:04 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:10:04 web:1635] 500 GET /db (54.184.112.97) 249.95ms
[E 140415 10:10:23 web:1228] Uncaught exception GET /queries?queries=2 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=2', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:10:23 web:1635] 500 GET /queries?queries=2 (54.184.112.97) 3.56ms
[E 140415 10:11:00 web:1228] Uncaught exception GET /queries?queries=1 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=1', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:11:00 web:1635] 500 GET /queries?queries=1 (54.184.112.97) 123.07ms
[E 140415 10:11:09 web:1228] Uncaught exception GET /queries?queries=5 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=5', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:11:09 web:1635] 500 GET /queries?queries=5 (54.184.112.97) 578.86ms
[E 140415 10:11:13 web:1228] Uncaught exception GET /queries?queries=5 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=5', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:11:13 web:1635] 500 GET /queries?queries=5 (54.184.112.97) 500.65ms
[E 140415 10:11:24 web:1228] Uncaught exception GET /queries?queries=10 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=10', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:11:24 web:1635] 500 GET /queries?queries=10 (54.184.112.97) 598.44ms
[E 140415 10:11:29 web:1228] Uncaught exception GET /queries?queries=10 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=10', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:11:29 web:1635] 500 GET /queries?queries=10 (54.184.112.97) 828.32ms
[E 140415 10:11:30 web:1228] Uncaught exception GET /queries?queries=10 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=10', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:11:30 web:1635] 500 GET /queries?queries=10 (54.184.112.97) 1605.18ms
[E 140415 10:11:32 web:1228] Uncaught exception GET /queries?queries=10 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=10', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:11:32 web:1635] 500 GET /queries?queries=10 (54.184.112.97) 1528.41ms
[E 140415 10:11:51 web:1228] Uncaught exception GET /queries?queries=15 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:11:51 web:1635] 500 GET /queries?queries=15 (54.184.112.97) 1420.40ms
[E 140415 10:11:54 web:1228] Uncaught exception GET /queries?queries=15 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:11:54 web:1635] 500 GET /queries?queries=15 (54.184.112.97) 1987.61ms
[E 140415 10:11:54 web:1228] Uncaught exception GET /queries?queries=15 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:11:54 web:1635] 500 GET /queries?queries=15 (54.184.112.97) 1271.84ms
[E 140415 10:11:55 web:1228] Uncaught exception GET /queries?queries=15 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:11:55 web:1635] 500 GET /queries?queries=15 (54.184.112.97) 1182.53ms
[E 140415 10:11:56 web:1228] Uncaught exception GET /queries?queries=15 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:11:56 web:1635] 500 GET /queries?queries=15 (54.184.112.97) 938.73ms
[E 140415 10:12:00 web:1228] Uncaught exception GET /queries?queries=20 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=20', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:12:00 web:1635] 500 GET /queries?queries=20 (54.184.112.97) 2039.92ms
[E 140415 10:12:02 web:1228] Uncaught exception GET /queries?queries=20 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=20', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:12:02 web:1635] 500 GET /queries?queries=20 (54.184.112.97) 2372.22ms
[E 140415 10:12:05 web:1228] Uncaught exception GET /queries?queries=20 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=20', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:12:05 web:1635] 500 GET /queries?queries=20 (54.184.112.97) 2441.19ms
[E 140415 10:12:11 web:1228] Uncaught exception GET /queries?queries=20 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=20', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py3/lib/python3.3/site-packages/tornado-3.1-py3.3.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:12:11 web:1635] 500 GET /queries?queries=20 (54.184.112.97) 2022.75ms
