[E 140415 09:59:16 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 09:59:16 web:1635] 500 GET /db (54.184.112.97) 26.85ms
[E 140415 09:59:16 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 09:59:16 web:1635] 500 GET /db (54.184.112.97) 6.45ms
[E 140415 09:59:46 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 09:59:46 web:1635] 500 GET /db (54.184.112.97) 14.15ms
[E 140415 09:59:47 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 09:59:47 web:1635] 500 GET /db (54.184.112.97) 16.73ms
[E 140415 09:59:50 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 09:59:50 web:1635] 500 GET /db (54.184.112.97) 14.05ms
[E 140415 10:00:02 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:00:02 web:1635] 500 GET /db (54.184.112.97) 47.93ms
[E 140415 10:00:06 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:00:06 web:1635] 500 GET /db (54.184.112.97) 33.09ms
[E 140415 10:00:07 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:00:07 web:1635] 500 GET /db (54.184.112.97) 32.84ms
[E 140415 10:00:19 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:00:19 web:1635] 500 GET /db (54.184.112.97) 48.64ms
[E 140415 10:00:22 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:00:22 web:1635] 500 GET /db (54.184.112.97) 89.00ms
[E 140415 10:00:30 web:1228] Uncaught exception GET /db (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/db', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 46, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:00:30 web:1635] 500 GET /db (54.184.112.97) 65.01ms
[E 140415 10:00:55 web:1228] Uncaught exception GET /queries?queries=2 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=2', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:00:55 web:1635] 500 GET /queries?queries=2 (54.184.112.97) 13.15ms
[E 140415 10:01:04 web:1228] Uncaught exception GET /queries?queries=2 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=2', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:01:04 web:1635] 500 GET /queries?queries=2 (54.184.112.97) 149.85ms
[E 140415 10:01:06 web:1228] Uncaught exception GET /queries?queries=2 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=2', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:01:06 web:1635] 500 GET /queries?queries=2 (54.184.112.97) 260.75ms
[E 140415 10:01:15 web:1228] Uncaught exception GET /queries?queries=2 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=2', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:01:15 web:1635] 500 GET /queries?queries=2 (54.184.112.97) 292.39ms
[E 140415 10:01:38 web:1228] Uncaught exception GET /queries?queries=5 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=5', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:01:38 web:1635] 500 GET /queries?queries=5 (54.184.112.97) 388.51ms
[E 140415 10:01:42 web:1228] Uncaught exception GET /queries?queries=5 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=5', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:01:42 web:1635] 500 GET /queries?queries=5 (54.184.112.97) 660.44ms
[E 140415 10:01:47 web:1228] Uncaught exception GET /queries?queries=5 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=5', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:01:47 web:1635] 500 GET /queries?queries=5 (54.184.112.97) 419.70ms
[E 140415 10:01:52 web:1228] Uncaught exception GET /queries?queries=5 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=5', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:01:52 web:1635] 500 GET /queries?queries=5 (54.184.112.97) 649.23ms
[E 140415 10:02:01 web:1228] Uncaught exception GET /queries?queries=10 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=10', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:02:01 web:1635] 500 GET /queries?queries=10 (54.184.112.97) 1049.87ms
[E 140415 10:02:04 web:1228] Uncaught exception GET /queries?queries=10 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=10', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:02:04 web:1635] 500 GET /queries?queries=10 (54.184.112.97) 1059.28ms
[E 140415 10:02:20 web:1228] Uncaught exception GET /queries?queries=15 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:02:20 web:1635] 500 GET /queries?queries=15 (54.184.112.97) 1110.94ms
[E 140415 10:02:26 web:1228] Uncaught exception GET /queries?queries=15 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:02:26 web:1635] 500 GET /queries?queries=15 (54.184.112.97) 1158.40ms
[E 140415 10:02:33 web:1228] Uncaught exception GET /queries?queries=20 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=20', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:02:33 web:1635] 500 GET /queries?queries=20 (54.184.112.97) 2414.17ms
[E 140415 10:02:35 web:1228] Uncaught exception GET /queries?queries=20 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=20', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:02:35 web:1635] 500 GET /queries?queries=20 (54.184.112.97) 1388.86ms
[E 140415 10:02:41 web:1228] Uncaught exception GET /queries?queries=20 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=20', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:02:41 web:1635] 500 GET /queries?queries=20 (54.184.112.97) 2547.76ms
[E 140415 10:02:44 web:1228] Uncaught exception GET /queries?queries=20 (54.184.112.97)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=20', version='HTTP/1.1', remote_ip='54.184.112.97', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/ubuntu/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 507, in run
        yielded = self.gen.send(next)
      File "server.py", line 69, in get
        world['id'] = str(world.pop('_id'))
    AttributeError: 'NoneType' object has no attribute 'pop'
[E 140415 10:02:44 web:1635] 500 GET /queries?queries=20 (54.184.112.97) 2154.68ms
